version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
